// Word Bank: Dutch (Nederlands)
class DutchWords {
  static const List<String> list = [
    'LEEUW','TIJGER','OLIFANT','PAARD','HOND','KAT','BEER','WOLF','VOS','AAP','KONIJN','HERT','GIRAF','NIJLPAARD','NEUSHOORN','EZEL','KOE','STIER','SCHAAP','GEIT','VARKEN','EEKHOORN','MUIS','SCHILDPAD','KROKODIL','SLANG','KIKKER','VIS','AREND','KRAAI','PAPEGAAI','HAAN','EEND','UIL','PAUW','DUIF','MUS',
    'APPEL','BANAAN','SINAASAPPEL','DRUIF','GRANAATAPPEL','WATERMELOEN','MELOEN','PERZIK','ABRIKOOS','KERS','CITROEN','PEER','PRUIM','AARDBEI','FRAMBOOS','ANANAS','AARDAPPEL','UI','TOMAAT','ERWT','WORTEL','RADIJS','SPINAZIE','KOOL','AUBERGINE','KOMKOMMER','KNOFLOOK','PEPER','KORIANDER','SLA',
    'ZON','MAAN','STER','HEMEL','AARDE','RIVIER','ZEE','OCEOAN','BERG','WATERVAL','MEER','WOLK','REGEN','WIND','VUUR','WATER','BODEM','BOS','BLOEM','BOOM','PLANT','BLAD','TAK','WORTEL','ZAAD','ZAND','STEEN','GROT','WOESTIJN','EILAND','VALLEI','STORM','SNEEUW','MIST','LICHT','SCHADUW',
    'HUIS','KAMER','DEUR','RAAM','MUUR','DAK','VLOER','STOEL','TAFEL','BED','KUSSEN','DEKEN','GORDIJN','KAST','SPIEGEL','LAMP','VENTILATOR','KLOK','SLOT','SLEUTEL','BORD','GLAS','LEPEL','MES','SCHAAR','NAALD','DRAAD','KLEDING','SCHOEN','TAS','FLES','PEN','BOEK','PAPIER','POTLOOD',
    'MOEDER','VADER','BROER','ZUS','ZOON','DOCHTER','GROOTVADER','GROOTMOEDER','OOM','TANTE','VRIEND','VRIENDIN','KIND','MAN','VROUW','MENS','KONING','KONINGIN','LERAAR','DOKTER','BOER','DICHTER','SCHRIJVER','ZANGER','ACTEUR','LAND','STAD','DORP',
    'LIEFDE','WAARHEID','VREDE','VREUGDE','GELUK','HOOP','DROOM','MOED','GEDULD','GOEDHEID','WIJSHEID','ONDERWIJS','SUCCES','OVERWINNING','GELOOF','DIENST','EENHEID','VRIJHEID','ENTHOUSIASME',
    'ROOD','GROEN','BLAUW','GEEL','WIT','ZWART','ROZE','PAARS','ORANJE','BRUIN','GOUD','ZILVER','ROND','LANG','BREED','GROOT','KLEIN','ZOET','ZURE','SCHERP','HEET','KOUD','TIJD','VANDAAG','MORGEN','OCHTEND','MIDDAG','AVOND','NACHT','DAG','JAAR'
  ];
}
