// Word Bank: French (Français)
class FrenchWords {
  static const List<String> list = [
    'LION','TIGRE','ELEPHANT','CHEVAL','CHIEN','CHAT','OURS','LOUP','RENARD','SINGE','LAPIN','CERF','GIRAFE','HIPPOPOTAME','RHINOCEROS','ANE','VACHE','TAUREAU','MOUTON','CHEVRE','COCHON','ECUREUIL','SOURIS','TORTUE','CROCODILE','SERPENT','GRENOUILLE','POISSON','AIGLE','CORBEAU','PERROQUET','COQ','CANARD','HIBOU','PAON','PIGEON','MOINEAU',
    'POMME','BANANE','ORANGE','RAISIN','GRENADE','PASTEQUE','MELON','PECHE','ABRICOT','CERISE','CITRON','POIRE','PRUNE','FRAISE','FRAMBOISE','ANANAS','POMMEDETERRE','OIGNON','TOMATE','PETITPOIS','CAROTTE','RADIS','EPINARD','CHOU','AUBERGINE','CONCOMBRE','AIL','POIVRON','CORIANDRE','LAITUE',
    'SOLEIL','LUNE','ETOILE','CIEL','TERRE','RIVIERE','MER','OCEAN','MONTAGNE','CASCADE','LAC','NUAGE','PLUIE','VENT','FEU','EAU','SOL','FORET','FLEUR','ARBRE','PLANTE','FEUILLE','BRANCHE','RACINE','GRAINE','SABLE','PIERRE','GROTTE','DESERT','ILE','VALLEE','TEMPETE','NEIGE','BROUILLARD','LUMIERE','OMBRE',
    'MAISON','CHAMBRE','PORTE','FENETRE','MUR','TOIT','SOL','CHAISE','TABLE','LIT','OREILLER','COUVERTURE','RIDEAU','ARMOIRE','MIROIR','LAMPE','VENTILATEUR','HORLOGE','SERRURE','CLE','ASSIETTE','VERRE','CUILLERE','COUTEAU','CISEAUX','AIGUILLE','FIL','VETEMENT','CHAUSSURE','SAC','BOUTEILLE','STYLO','LIVRE','PAPIER','CRAYON',
    'MERE','PERE','FRERE','SOEUR','FILS','FILLE','GRANDPERE','GRANDMERE','ONCLE','TANTE','AMI','AMIE','ENFANT','HOMME','FEMME','PERSONNE','ROI','REINE','PROFESSEUR','MEDECIN','FERMIER','POETE','ECRIVAIN','CHANTEUR','ACTEUR','PAYS','VILLE','VILLAGE',
    'AMOUR','VERITE','PAIX','JOIE','BONHEUR','ESPOIR','REVE','COURAGE','PATIENCE','BONTE','SAGESSE','EDUCATION','SUCCES','VICTOIRE','FOI','SERVICE','UNITE','LIBERTE','ENTHOUSIASME',
    'ROUGE','VERT','BLEU','JAUNE','BLANC','NOIR','ROSE','VIOLET','ORANGE','MARRON','OR','ARGENT','ROND','LONG','LARGE','GRAND','PETIT','DOUX','ACIDE','EPICE','CHAUD','FROID','TEMPS','AUJOURDHUI','DEMAIN','MATIN','MIDI','SOIR','NUIT','JOUR','ANNEE'
  ];
}
