// Word Bank: German (Deutsch) — Verified authentic dictionary words
class GermanWords {
  static const List<String> list = [
    // Animals & Birds (Tiere und Vögel)
    'LOEWE','TIGER','ELEFANT','PFERD','HUND','KATZE','BAER','WOLF','FUCHS','AFFEN','HASE','HIRSCH','GIRAFFE','FLUSSPFERD','NASHORN','ESEL','KUH','STIER','SCHAF','ZIEGE','SCHWEIN','EICHHOERNCHEN','MAUS','SCHILDKROETE','KROKODIL','SCHLANGE','FROSCH','FISCH','ADLER','KRAEHE','PAPAGEI','HAHN','ENTE','EULE','PFAU','TAUBE','SPATZ','SCHWALBE','SPECHT',
    // Fruits, Vegetables & Food (Obst, Gemüse und Essen)
    'APFEL','BANANE','ORANGE','TRAUBE','GRANATAPFEL','WASSERMELONE','MELONE','PFIRSICH','APRIKOSE','KIRSCHE','ZITRONE','BIRNE','PFLAUME','ERDBEERE','HIMBEERE','ANANAS','KARTOFFEL','ZWIEBEL','TOMATE','ERBSE','KAROTTE','RETTICH','SPINAT','KOHL','AUBERGINE','GURKE','KNOBLAUCH','PFEFFER','KORIANDER','SALAT','BROT','KAESE','MILCH','BUTTER','HONIG','REIS','SUPPE',
    // Nature, Earth & Science (Natur, Erde und Wissenschaft)
    'SONNE','MOND','STERN','HIMMEL','ERDE','FLUSS','MEER','OZEAN','BERG','WASSERFALL','SEE','WOLKE','REGEN','WIND','FEUER','WASSER','BODEN','WALD','BLUME','BAUM','PFLANZE','BLATT','AST','WURZEL','SAMEN','SAND','STEIN','HOEHLE','WUESTE','INSEL','TAL','STURM','SCHNEE','NEBEL','LICHT','SCHATTEN','BLITZ','DONNER',
    // Household & Everyday Items (Haushalt und Alltagsgegenstände)
    'HAUS','ZIMMER','TUER','FENSTER','WAND','DACH','BODEN','STUHL','TISCH','BETT','KISSEN','DECKE','VORHANG','SCHRANK','SPIEGEL','LAMPE','VENTILATOR','UHR','SCHLOSS','SCHLUESSEL','TELLER','GLAS','LOEFFEL','MESSER','SCHERE','NADEL','FADEN','KLEIDUNG','SCHUH','TASCHE','FLASCHE','STIFT','BUCH','PAPIER','BLEISTIFT','EIMER','KRUG',
    // People, Society & Relations (Menschen, Gesellschaft und Beziehungen)
    'MUTTER','VATER','BRUDER','SCHWESTER','SOHN','TOCHTER','GROSSVATER','GROSSMUTTER','ONKEL','TANTE','FREUND','FREUNDIN','KIND','MANN','FRAU','MENSCH','KOENIG','KOENIGIN','LEHRER','ARZT','BAUER','DICHTER','SCHRIFTSTELLER','SAENGER','SCHAUSPIELER','LAND','STADT','DORF','BURGERMEISTER','PRASIDENT',
    // Values, Culture & Time (Werte, Kultur und Zeit)
    'LIEBE','WAHRHEIT','FRIEDEN','FREUDE','GLUECK','HOFFNUNG','TRAUM','MUT','GEDULD','GUETE','WEISHEIT','BILDUNG','ERFOLG','SIEG','GLAUBE','DIENST','EINHEIT','FREIHEIT','BEGEISTERUNG','GEDICHT','MAERCHEN','GESCHICHTE','PRUEFUNG','ZEIT','HEUTE','MORGEN','MORGENS','MITTAGS','ABENDS','NACHT','TAG','JAHR'
  ];
}
