// Word Bank: Indonesian (Bahasa Indonesia) — Verified authentic dictionary words
class IndonesianWords {
  static const List<String> list = [
    // Animals & Birds (Hewan dan Burung)
    'SINGA','HARIMAU','GAJAH','KUDA','ANJING','KUCING','BERUANG','SERIGALA','RUBAH','MONYET','KELINCI','RUSA','JERAPAH','KUDANIL','BADAK','KELEDAI','SAPI','BANTENG','DOMBA','KAMBING','BABI','TUPAI','TIKUS','KURA-KURA','BUAYA','ULAR','KATAK','IKAN','ELANG','GAGAK','BEO','AYAM','BEBEK','BURUNGHANTU','MERAK','MERPATI','BURUNG','CENDRAWASIH','PIPIT',
    // Fruits, Vegetables & Food (Buah, Sayur dan Makanan)
    'APEL','PISANG','JERUK','ANGGUR','DELIMA','SEMANGKA','MELON','PERSIK','APRIKOT','CERI','MON','PIR','SUBAN','STROBERI','AMER','NANAS','KENTANG','BAWANG','TOMAT','KACANG','WORTEL','LOBAK','BAYAM','KUBIS','TERONG','MENTIMUN','BAWANGPUTIH','CABAI','KETUMBAR','SELADA','ROTI','KEJU','SUSU','MENTEGA','MADU','NASI','SUP',
    // Nature, Earth & Science (Alam, Bumi dan Sains)
    'MATAHARI','BULAN','BINTANG','LANGIT','BUMI','SUNGAI','LAUT','SAMUDRA','GUNUNG','AIRTERJUN','DANAU','AWAN','HUJAN','ANGIN','API','AIR','TANAH','HUTAN','BUNGA','POHON','TANAMAN','DAUN','DANTING','AKAR','BIJI','PASIR','BATU','GUA','GURUN','PULAU','LEMBAH','BADAI','SALJU','KABUT','CAHAYA','BAYANGAN','KILAT','PETIR',
    // Household & Everyday Items (Barang Rumah Tangga)
    'RUMAH','KAMAR','PINTU','JENDELA','DINDING','ATAP','LANTAI','KURSI','MEJA','KASUR','BANTAL','SELIMUT','TIRAI','LEMARI','CERMIN','LAMPU','KIPAS','JAM','KUNCI','PIRING','GELAS','SENDOK','PISAU','GUNTING','JARUM','BENANG','PAKAIAN','SEPATU','TAS','BOTOL','PENA','BUKU','KERTAS','PENSIL','EMBER','CANGKIR',
    // People, Society & Relations (Manusia, Masyarakat dan Hubungan)
    'IBU','AYAH','SAUDARA','SAUDARI','ANAK','PUTRI','KAKEK','NENEK','PAM AN','BIBI','TEMAN','SAHABAT','PRIA','WANITA','MANUSIA','RAJA','RATU','GURU','DOKTER','PETANI','PENYAIR','PENULIS','PENYANYI','AKTOR','NEGARA','KOTA','DESA','WALIKOTA','PRESIDEN',
    // Values, Culture & Time (Nilai, Budaya dan Waktu)
    'CINTA','KEBENARAN','KEDAMAIAN','KEGEMBIRAAN','KEBAHAGIAAN','HARAPAN','MIMPI','KEBERANIAN','KESABARAN','KEBAIKAN','KEBIJAKSANAAN','PENDIDIKAN','SUKSES','KEMENANGAN','IMAN','PELAYANAN','PERSATUAN','KEBEBASAN','SEMANGAT','PUISI','CERITA','TEATER','UJIAN','WAKTU','HARIINI','BESOK','PAGI','SIANG','SORE','MALAM','HARI','TAHUN'
  ];
}
