// Word Bank: Italian (Italiano) — Verified authentic dictionary words
class ItalianWords {
  static const List<String> list = [
    // Animals & Birds (Animali e Uccelli)
    'LEONE','TIGRE','ELEFANTE','CAVALLO','CANE','GATTO','ORSO','LUPO','VOLPE','SCIMMIA','CONIGLIO','CERVO','GIRAFFA','IPPOPOTAMO','RINOCERONTE','ASINO','MUCCA','TORO','PECORA','CAPRA','MAIALE','SCOIATTOLO','TOPO','TARTARUGA','COCCODRILLO','SERPENTE','RANA','PESCE','AQUILA','CORVO','PAPPAGALLO','GALLO','ANATRA','GUFO','PAONE','COLOMBA','PASSERO','RONDINE','PICCHIO',
    // Fruits, Vegetables & Food (Frutta, Verdura e Cibo)
    'MELA','BANANA','ARANCIA','UVA','MELAGRANA','ANGURIA','MELONE','PESCA','ALBICOCCA','CILIEGIA','LIMONE','PERA','PRUGNA','FRAGOLA','LAMPONE','ANANAS','PATATA','CIPOLLA','POMODORO','PISELLO','CAROTA','RAVANELLO','SPINACI','CAVOLO','MELANZANA','CETRIOLO','AGLIO','PEPERONE','CORIANDOLO','LATTUGA','PANE','FORMAGGIO','LATTE','BURRO','MIELE','RISO','ZUPPA',
    // Nature, Earth & Science (Natura, Terra e Scienza)
    'SOLE','LUNA','STELLA','CIELO','TERRA','FIUME','MARE','OCEANO','MONTAGNA','CASCATA','LAGO','NUVOLA','PIOGGIA','VENTO','FUOCO','ACQUA','SUOLO','FORESTA','FIORE','ALBERO','PIANTA','FOGLIA','RAMO','RADICE','SEME','SABBIA','PIETRA','GROTTA','DESERTO','ISOLA','VALLE','TEMPESTA','NEVE','NEBBIA','LUCE','OMBRA','FULMINE','TUONO',
    // Household & Everyday Items (Casa e Oggetti Quotidiani)
    'CASA','STANZA','PORTA','FINESTRA','MURO','TETTO','PAVIMENTO','SEDIA','TAVOLO','LETTO','CUSCINO','COPERTA','TENDA','ARMADIO','SPECCHIO','LAMPADA','VENTILATORE','OROLOGIO','SERRATURA','CHIAVE','PIATTO','BICCHIERE','CUCCHIAIO','COLTELLO','FORBICI','AGO','FILO','ABITO','SCARPA','BORSA','BOTTIGLIA','PENNA','LIBRO','CARTA','MATITA','SECCHIO','CARAFFA',
    // People, Society & Relations (Persone, Società e Relazioni)
    'MADRE','PADRE','FRATELLO','SORELLA','FIGLIO','FIGLIA','NONNO','NONNA','ZIO','ZIA','AMICO','AMICA','BAMBINO','UOMO','DONNA','PERSONA','RE','REGINA','INSEGNANTE','MEDICO','CONTADINO','POETA','SCRITTORE','CANTANTE','ATTORE','PAESE','CITTA','VILLAGGIO','SINDACO','PRESIDENTE',
    // Values, Culture & Time (Valori, Cultura e Tempo)
    'AMORE','VERITA','PACE','GIOIA','FELICITA','SPERANZA','SOGNO','CORAGGIO','PAZIENZA','BONTA','SAGGEZZA','EDUCAZIONE','SUCCESSO','VITTORIA','FEDE','SERVIZIO','UNITA','LIBERTA','ENTUSIASMO','POESIA','FAVOLA','RACCONTO','ESAME','TEMPO','OGGI','DOMANI','MATTINA','MEZZOGIORNO','SERA','NOTTE','GIORNO','ANNO'
  ];
}
