// Word Bank: Portuguese (Português) — Verified authentic dictionary words
class PortugueseWords {
  static const List<String> list = [
    // Animals & Birds (Animais e Aves)
    'LEAO','TIGRE','ELEFANTE','CAVALO','CAO','GATO','URSO','LOBO','RAPOSA','MACACO','COELHO','VEADO','GIRAFA','HIPOPOTAMO','RINOCERONTE','BURRO','VACA','TOURO','OVELHA','CABRA','PORCO','ESQUILO','RATO','TARTARUGA','CROCODILO','COBRA','SAPO','PEIXE','AGUIA','CORVO','PAPAGAIO','GALO','PATO','CORUJA','PAVAO','POMBO','PARDAL','HIRONDELLE','PICA-PAU',
    // Fruits, Vegetables & Food (Frutas, Vegetais e Comida)
    'MACA','BANANA','LARANJA','UVA','ROMA','MELANCIA','MELAO','PESSEGO','DAMASCO','CEREJA','LIMAO','PERA','AMEIXA','MORANGO','FRAMBOESA','ANANAS','BATATA','CEBOLA','TOMATE','ERVILHA','CENOURA','RABANETE','ESPINAFRE','COUVE','BERINJELA','PEPINO','ALHO','PIMENTA','COENTRO','ALFACE','PAO','QUEIJO','LEITE','MANTEIGA','MEL','ARROZ','SOPA',
    // Nature, Earth & Science (Natureza, Terra e Ciência)
    'SOL','LUA','ESTRELA','CEU','TERRA','RIO','MAR','OCEANO','MONTANHA','CACHOEIRA','LAGO','NUVEM','CHUVA','VENTO','FOGO','AGUA','SOLO','FLORESTA','FLOR','ARVORE','PLANTA','FOLHA','RAMO','RAIZ','SEMENTE','AREIA','PEDRA','CAVERNA','DESERTO','ILHA','VALE','TEMPESTADE','NEVE','NEVOEIRO','LUZ','SOMBRA','RAIO','TROVAO',
    // Household & Everyday Items (Casa e Objetos Diários)
    'CASA','QUARTO','PORTA','JANELA','PAREDE','TETO','CHAO','CADEIRA','MESA','CAMA','ALMOFADA','COBERTOR','CORTINA','ARMARIO','ESPELHO','LAMPADA','VENTILADOR','RELOGIO','FECHADURA','CHAVE','PRATO','COPO','COLHER','FACA','TESOURA','AGULHA','FINO','ROUPA','SAPATO','BOLSA','GARRAFA','CANETA','LIVRO','PAPEL','LAPIS','BALDE','JARRA',
    // People, Society & Relations (Pessoas, Sociedade e Relações)
    'MAE','PAI','IRMAO','IRMA','FILHO','FILHA','AVO','AVO','TIO','TIA','AMIGO','AMIGA','CRIANCA','HOMEM','MULHER','PESSOA','REI','RAINHA','PROFESSOR','MEDICO','FAZENDEIRO','POETA','ESCRITOR','CANTOR','ATOR','PAIS','CIDADE','VILA','PREFEITO','PRESIDENTE',
    // Values, Culture & Time (Valores, Cultura e Tempo)
    'AMOR','VERDADE','PAZ','ALEGRIA','FELICIDADE','ESPERANCA','SONHO','CORAGEM','PACIENCIA','BONDADE','SABEDORIA','EDUCACAO','SUCESSO','VITORIA','FE','SERVICO','UNIDADE','LIBERDADE','ENTUSIASMO','POESIA','CONTO','TEATRO','EXAME','TEMPO','HOJE','AMANHA','MANHA','TARDE','NOITE','DIA','ANO'
  ];
}
