// Word Bank: Spanish (Español) — Verified authentic dictionary words
class SpanishWords {
  static const List<String> list = [
    // Animals & Birds (Animales y Aves)
    'LEON','TIGRE','ELEFANTE','CABALLO','PERRO','GATO','OSO','LOBO','ZORRO','MONO','CONEJO','CIERVO','JIRAFA','HIPOPOTAMO','RINOCERONTE','BURRO','VACA','TORO','OVEJA','CABRA','CERDO','ARDILLA','RATON','TORTUGA','COCODRILO','SERPIENTE','RANA','PEZ','AGUILA','CUERVO','LORO','GALLO','PATO','BUHO','PAVO','PALOMA','GORRION','COLIBRI','FLAMENCO','HALCON',
    // Fruits, Vegetables & Food (Frutas, Verduras y Comida)
    'MANZANA','BANANO','NARANJA','UVA','GRANADA','SANDIA','MELON','MELOCOTON','ALBARICOQUE','CEREZA','LIMON','PERA','CIRUELA','FRESA','FRAMBUESA','PIÑA','PAPA','CEBOLLA','TOMATE','GUISANTE','ZANAHORIA','RABANO','ESPINACA','COL','BERENJENA','PEPINO','AJO','PIMIENTA','CILANTRO','LECHUGA','PAN','QUESO','LECHE','MANTEQUILLA','MIEL','ARROZ','SOPA',
    // Nature, Earth & Science (Naturaleza, Tierra y Ciencia)
    'SOL','LUNA','ESTRELLA','CIELO','TIERRA','RIO','MAR','OCEANO','MONTAÑA','CASCADA','LAGO','NUBE','LLUVIA','VIENTO','FUEGO','AGUA','SUELO','BOSQUE','FLOR','ARBOL','PLANTA','HOJA','RAMA','RAIZ','SEMILLA','ARENA','PIEDRA','CUEVA','DESIERTO','ISLA','VALLE','TORMENTA','NIEVE','NIEBLA','LUZ','SOMBRA','RAYO','TRUENO','NUBARRON',
    // Household & Everyday Items (Hogar y Objetos Diarios)
    'CASA','HABITACION','PUERTA','VENTANA','PARED','TECHO','PISO','SILLA','MESA','CAMA','ALMOHADA','COBIJA','CORTINA','ARMARIO','ESPEJO','LAMPARA','VENTILADOR','RELOJ','CANDADO','LLAVE','PLATO','VASO','CUCHARA','CUCHILLO','TIJERAS','AGUJA','HILO','ROPA','ZAPATO','BOLSA','BOTELLA','PLUMA','LIBRO','PAPEL','LAPIZ','BALDE','JARRA',
    // People, Society & Relations (Personas, Sociedad y Relaciones)
    'MADRE','PADRE','HERMANO','HERMANA','HIJO','HIJA','ABUELO','ABUELA','TIO','TIA','AMIGO','AMIGA','NIÑO','HOMBRE','MUJER','PERSONA','REY','REINA','PROFESOR','DOCTOR','GRANJERO','POETA','ESCRITOR','CANTANTE','ACTOR','PAIS','CIUDAD','PUEBLO','ALCALDE','PRESIDENTE',
    // Values, Culture & Time (Valores, Cultura y Tiempo)
    'AMOR','VERDAD','PAZ','ALEGRIA','FELICIDAD','ESPERANZA','SUEÑO','VALOR','PACIENCIA','BONDAD','SABIDURIA','EDUCACION','EXITO','VICTORIA','FE','SERVICIO','UNIDAD','LIBERTAD','ENTUSIASMO','POESIA','CUENTO','TEATRO','EXAMEN','TIEMPO','HOY','MAÑANA','TARDE','NOCHE','DIA','AÑO'
  ];
}
