// Word Bank: Spanish (Español)
class SpanishWords {
  static const List<String> list = [
    'LEON','TIGRE','ELEFANTE','CABALLO','PERRO','GATO','OSO','LOBO','ZORRO','MONO','CONEJO','CIERVO','JIRAFA','HIPOPOTAMO','RINOCERONTE','BURRO','VACA','TORO','OVEJA','CABRA','CERDO','ARDILLA','RATON','TORTUGA','COCODRILO','SERPIENTE','RANA','PEZ','AGUILA','CUERVO','LORO','GALLO','PATO','BUHO','PAVO','PALOMA','GORRION',
    'MANZANA','BANANO','NARANJA','UVA','GRANADA','SANDIA','MELON','MELOCOTON','ALBARICOQUE','CEREZA','LIMON','PERA','CIRUELA','FRESA','FRAMBUESA','PIÑA','PAPA','CEBOLLA','TOMATE','GUISANTE','ZANAHORIA','RABANO','ESPINACA','COL','BERENJENA','PEPINO','AJO','PIMIENTA','CILANTRO','LECHUGA',
    'SOL','LUNA','ESTRELLA','CIELO','TIERRA','RIO','MAR','OCEANO','MONTAÑA','CASCADA','LAGO','NUBE','LLUVIA','VIENTO','FUEGO','AGUA','SUELO','BOSQUE','FLOR','ARBOL','PLANTA','HOJA','RAMA','RAIZ','SEMILLA','ARENA','PIEDRA','CUEVA','DESIERTO','ISLA','VALLE','TORMENTA','NIEVE','NIEBLA','LUZ','SOMBRA',
    'CASA','HABITACION','PUERTA','VENTANA','PARED','TECHO','PISO','SILLA','MESA','CAMA','ALMOHADA','COBIJA','CORTINA','ARMARIO','ESPEJO','LAMPARA','VENTILADOR','RELOJ','CANDADO','LLAVE','PLATO','VASO','CUCHARA','CUCHILLO','TIJERAS','AGUJA','HILO','ROPA','ZAPATO','BOLSA','BOTELLA','PLUMA','LIBRO','PAPEL','LAPIZ',
    'MADRE','PADRE','HERMANO','HERMANA','HIJO','HIJA','ABUELO','ABUELA','TIO','TIA','AMIGO','AMIGA','NIÑO','HOMBRE','MUJER','PERSONA','REY','REINA','PROFESOR','DOCTOR','GRANJERO','POETA','ESCRITOR','CANTANTE','ACTOR','PAIS','CIUDAD','PUEBLO',
    'AMOR','VERDAD','PAZ','ALEGRIA','FELICIDAD','ESPERANZA','SUEÑO','VALOR','PACIENCIA','BONDAD','SABIDURIA','EDUCACION','EXITO','VICTORIA','FE','SERVICIO','UNIDAD','LIBERTAD','ENTUSIASMO',
    'ROJO','VERDE','AZUL','AMARILLO','BLANCO','NEGRO','ROSADO','VIOLETA','NARANJA','MARRON','DORADO','PLATEADO','REDONDO','LARGO','ANCHO','GRANDE','PEQUEÑO','DULCE','ACIDO','PICANTE','CALIENTE','FRIO','TIEMPO','HOY','MAÑANA','MAÑANA','TARDE','NOCHE','DIA','AÑO'
  ];
}
