// Word Bank: Turkish (Türkçe)
class TurkishWords {
  static const List<String> list = [
    'ASLAN','KAPLAN','FIL','AT','KOPEK','KEDI','AYI','KURT','TILKI','MAYMUN','TAVSAN','GEYIK','ZURAFA','HIPOPOTAM','GERGEDAN','ESEK','INEK','BOGA','KOYUN','KECI','DOMUZ','SINCAP','FARE','KAPLUMBAĞA','TIMSAH','YILAN','KURBAGA','BALIK','KARTAL','KARGA','PAPAĞAN','HOROZ','ORDEK','BAYKUS','TAVUSKUSU','GUVERCIN','SERCE',
    'ELMA','MUZ','PORTAKAL','UZUM','NAR','KARPUZ','KAVUN','SEFTALI','KAYISI','KIRAZ','LIMON','ARMUT','ERIK','CILEK','AHUDUDU','ANANAS','PATATES','SOGAN','DOMATES','BEZELYE','HAVUC','TURP','ISPANAK','LAHANA','PATLICAN','SALATALIK','SARIMSAK','BIBER','MAYDANOZ','MARUL',
    'GUNES','AY','YILDIZ','GOKYUZU','DUNYA','NEHIR','DENIZ','OKYANUS','DAG','SELALE','GOL','BULUT','YAGMUR','RUZGAR','ATES','SU','TOPRAK','ORMAN','CICEK','AGAC','BITKI','YAPRAK','DAL','KOK','TOHUM','KUM','TAS','MAGARA','COL','ADA','VADI','FIRTINA','KAR','SIS','ISIK','GOLGE',
    'EV','ODA','KAPI','PENCERE','DUVAR','CATI','ZEMIN','SANDALYE','MASA','YATAK','YASTIK','YORGAN','PERDE','DOLAP','AYNA','LAMBA','FAN','SAAT','KILIT','ANAHTAR','TABAK','BARDAK','KASIK','BICAK','MAKAS','IGNE','IPLIK','ELBISE','AYAKKABI','CANTA','SISE','KALEM','KITAP','KAGIT','KURSNKALEM',
    'ANNE','BABA','ERKEKKARDES','KIZKARDES','OGUL','KIZ','DEDE','NENE','AMCA','HALA','ARKADAS','DOST','COCUK','ADAM','KADIN','INSAN','KRAL','KRALICE','OGRETMEN','DOKTOR','CIFTCI','SAIR','YAZAR','SHARKISEVER','OYUNCU','ULKE','SEHIR','KOY',
    'SEVGI','GERCEK','BARIS','NESE','MUTLULUK','UMUT','HAYAL','CESARET','SABIR','IYILIK','BILGELIK','EGITIM','BASARI','ZAFER','INANC','HIZMET','BIRLIK','OZGURLUK','HEVES',
    'KIRMIZI','YESIL','MAVI','SARI','BEYAZ','SIYAH','PEMBE','MOR','TURUNCU','KAHVERENGI','ALTIN','GUMUS','YUVARLAK','UZUN','GENIS','BUYUK','KUCUK','TATLI','EKSI','ACI','SICAK','SOGUK','ZAMAN','BUGUN','YARIN','SABAH','OGLEN','AKSAM','GECE','GUN','YIL'
  ];
}
