// Word Bank: Turkish (Türkçe) — Verified authentic dictionary words
class TurkishWords {
  static const List<String> list = [
    // Animals & Birds (Hayvanlar ve Kuşlar)
    'ASLAN','KAPLAN','FIL','AT','KOPEK','KEDI','AYI','KURT','TILKI','MAYMUN','TAVSAN','GEYIK','ZURAFA','HIPOPOTAM','GERGEDAN','ESEK','INEK','BOGA','KOYUN','KECI','DOMUZ','SINCAP','FARE','KAPLUMBAĞA','TIMSAH','YILAN','KURBAGA','BALIK','KARTAL','KARGA','PAPAĞAN','HOROZ','ORDEK','BAYKUS','TAVUSKUSU','GUVERCIN','SERCE','KIRLANGIC','AGACKAKAN',
    // Fruits, Vegetables & Food (Meyveler, Sebzeler ve Yemek)
    'ELMA','MUZ','PORTAKAL','UZUM','NAR','KARPUZ','KAVUN','SEFTALI','KAYISI','KIRAZ','LIMON','ARMUT','ERIK','CILEK','AHUDUDU','ANANAS','PATATES','SOGAN','DOMATES','BEZELYE','HAVUC','TURP','ISPANAK','LAHANA','PATLICAN','SALATALIK','SARIMSAK','BIBER','MAYDANOZ','MARUL','EKMEK','PEYNIR','SUT','TEREYAGI','BAL','PIRINC','CORBA',
    // Nature, Earth & Science (Doğa, Dünya ve Bilim)
    'GUNES','AY','YILDIZ','GOKYUZU','DUNYA','NEHIR','DENIZ','OKYANUS','DAG','SELALE','GOL','BULUT','YAGMUR','RUZGAR','ATES','SU','TOPRAK','ORMAN','CICEK','AGAC','BITKI','YAPRAK','DAL','KOK','TOHUM','KUM','TAS','MAGARA','COL','ADA','VADI','FIRTINA','KAR','SIS','ISIK','GOLGE','SIMSEK','GOKGURULTUSU',
    // Household & Everyday Items (Ev ve Günlük Eşyalar)
    'EV','ODA','KAPI','PENCERE','DUVAR','CATI','ZEMIN','SANDALYE','MASA','YATAK','YASTIK','YORGAN','PERDE','DOLAP','AYNA','LAMBA','FAN','SAAT','KILIT','ANAHTAR','TABAK','BARDAK','KASIK','BICAK','MAKAS','IGNE','IPLIK','ELBISE','AYAKKABI','CANTA','SISE','KALEM','KITAP','KAGIT','KURSNKALEM','KOVA','SURAHI',
    // People, Society & Relations (İnsanlar, Toplum ve İlişkiler)
    'ANNE','BABA','ERKEKKARDES','KIZKARDES','OGUL','KIZ','DEDE','NENE','AMCA','HALA','ARKADAS','DOST','COCUK','ADAM','KADIN','INSAN','KRAL','KRALICE','OGRETMEN','DOKTOR','CIFTCI','SAIR','YAZAR','SHARKISEVER','OYUNCU','ULKE','SEHIR','KOY','BELEDIYEBASKANI','CUMHURBASKANI',
    // Values, Culture & Time (Değerler, Kültür ve Zaman)
    'SEVGI','GERCEK','BARIS','NESE','MUTLULUK','UMUT','HAYAL','CESARET','SABIR','IYILIK','BILGELIK','EGITIM','BASARI','ZAFER','INANC','HIZMET','BIRLIK','OZGURLUK','HEVES','SIIR','MASAL','HIKAYE','SINAV','ZAMAN','BUGUN','YARIN','SABAH','OGLEN','AKSAM','GECE','GUN','YIL'
  ];
}
